# Generated by Django 4.1.2 on 2023-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Activity_of_employer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Additional_information',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Job_posted_days',
        ),
        migrations.AlterField(
            model_name='job',
            name='Experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='Salary',
            field=models.CharField(max_length=20),
        ),
    ]
