# Generated by Django 4.1.3 on 2023-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Qualification', models.TextField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('Mobile', models.IntegerField()),
                ('City', models.CharField(max_length=20)),
                ('Salary_Expectation', models.CharField(max_length=50)),
                ('Current_Locatin', models.CharField(max_length=20)),
                ('Preferrable_Location', models.CharField(max_length=500)),
            ],
        ),
    ]
